import assert from "node:assert/strict";
import { build, preview } from "vite";
import react from "@vitejs/plugin-react";
import { chromium } from "playwright";
import os from "node:os";
import path from "node:path";
import fs from "node:fs";

const outDir = fs.mkdtempSync(path.join(os.tmpdir(), "jaos-education-ui-"));
await build({ configFile: false, plugins: [react()], build: { outDir, rollupOptions: { input: "tests/education-ui.html" } } });
const server = await preview({ configFile: false, build: { outDir }, preview: { host: "127.0.0.1", port: 4179, strictPort: true } });
console.log("UI fixture built; launching headless browser");
const browser = await chromium.launch({ channel: "msedge", headless: true, timeout: 30000 });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 1080 } });
  const errors = [];
  page.on("pageerror", (error) => errors.push(error.message));
  await page.goto("http://127.0.0.1:4179/tests/education-ui.html", { waitUntil: "domcontentloaded" });
  console.log("UI fixture loaded");
  await page.locator('[name="role"]').selectOption("education");
  assert.equal(await page.locator('[name="confidentiality_ceiling"]').inputValue(), "L1");
  assert.equal(await page.locator('[name="confidentiality_ceiling"] option:disabled').count(), 4);
  await page.getByRole("button", { name: /2026年10月托管教培班/ }).click();
  await page.getByRole("heading", { name: "追加收入 / 支出" }).waitFor();
  assert.equal(await page.locator('.educationCohortDelete').count(), 0);
  await page.getByLabel("金额（元）", { exact: true }).fill("2500.50");
  await page.getByLabel("收支用途", { exact: true }).fill("补缴学费");
  await page.getByRole("button", { name: "追加收支", exact: true }).click();
  await page.getByText("本期公共收支明细（3）").waitFor();
  assert.match(await page.locator('.educationMetrics').first().innerText(), /12,500.50/);
  const added = page.locator('.educationEntries article').filter({ hasText: "补缴学费" });
  await added.getByRole("button", { name: "修正", exact: true }).click();
  await page.getByLabel("金额（元）", { exact: true }).fill("2000.50");
  await page.getByRole("button", { name: "保存修正", exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.educationMetrics')?.textContent.includes('12,000.50'));
  await page.getByText("编辑班期、招生人数和客单价", { exact: true }).click();
  await page.locator('.educationDetail [name="student_count"]').fill("14");
  await page.getByRole("button", { name: "保存班期", exact: true }).click();
  await page.waitForFunction(() => document.querySelector('.educationMetrics')?.textContent.includes('49,007.00'));
  await page.getByText("＋ 新增学员报名", { exact: true }).click();
  const enrollment = page.locator('form').filter({ has: page.getByRole('button', { name: '保存报名', exact: true }) });
  await enrollment.getByLabel('学员姓名', { exact: true }).fill('测试学员');
  await enrollment.getByLabel('年龄', { exact: true }).fill('18');
  await enrollment.getByLabel('身份证号', { exact: true }).fill('110101200801011234');
  await enrollment.getByLabel('联系电话', { exact: true }).fill('13812345678');
  await enrollment.locator('[name="game"]').selectOption('CS2');
  await enrollment.getByLabel('应收（元）', { exact: true }).fill('5000');
  await enrollment.getByLabel('成本（元）', { exact: true }).fill('1200');
  await enrollment.getByLabel('已收金额（累计，元）', { exact: true }).fill('4000');
  await enrollment.getByRole('button', { name: '保存报名', exact: true }).click();
  await page.locator('.educationStudentList article').filter({ hasText: '测试学员' }).waitFor();
  assert.match(await page.locator('.educationStudentList').innerText(), /1,000.00/);
  assert.doesNotMatch(await page.locator('.educationStudentList').innerText(), /110101200801011234|13812345678/);
  await page.getByRole('button', { name: '教练评估', exact: true }).click();
  const assessment = page.locator('.educationAssessments');
  const fillAssessment = async (observation) => {
    await assessment.locator('[name="evaluator_staff_id"]').selectOption('teacher-1');
    await assessment.getByLabel('客观观察与证据', { exact: true }).fill(observation);
    await assessment.locator('[name="score_团队协作"]').selectOption('3');
  };
  await fillAssessment('入营训练中能够完成基础配合，需提升沟通。');
  await assessment.getByRole('button', { name: '保存评估记录', exact: true }).click();
  await assessment.getByText('成长记录（1）', { exact: true }).waitFor();
  await assessment.getByRole('button', { name: '阶段观察', exact: true }).click();
  await fillAssessment('第1周沟通次数增加，复盘执行仍需提醒。');
  await assessment.getByLabel('评估阶段名称', { exact: true }).fill('第1周基础训练');
  await assessment.getByRole('button', { name: '保存评估记录', exact: true }).click();
  await assessment.getByText('成长记录（2）', { exact: true }).waitFor();
  await assessment.getByRole('button', { name: '结营评估', exact: true }).click();
  await fillAssessment('结营配合练习能够主动报点。');
  await assessment.getByLabel('结营综合结论', { exact: true }).fill('团队沟通有进步，继续巩固基础。');
  await assessment.getByLabel('未来预期 · 保守情景', { exact: true }).fill('保持当前基础表现。');
  await assessment.getByLabel('未来预期 · 乐观情景', { exact: true }).fill('持续练习后有望提升稳定性。');
  await assessment.getByLabel('预期依据、前提与不确定性', { exact: true }).fill('基于本期记录，取决于持续练习和复盘。');
  await assessment.getByRole('button', { name: '保存评估记录', exact: true }).click();
  await assessment.getByText('成长记录（3）', { exact: true }).waitFor();
  await assessment.getByRole('button', { name: '生成 / 查看结营报告', exact: true }).click();
  await page.locator('.educationReport pre').waitFor();
  assert.match(await page.locator('.educationReport pre').innerText(), /团队沟通有进步/);
  assert.doesNotMatch(await page.locator('.educationReport pre').innerText(), /110101200801011234|13812345678/);
  const downloadEvent = page.waitForEvent('download');
  await page.getByRole('button', { name: '下载结营报告（TXT）', exact: true }).click();
  assert.match((await downloadEvent).suggestedFilename(), /结营报告.txt$/);
  assert.equal(await page.locator('[name="education_cohort_name"]').first().getAttribute('autocomplete'), 'off');
  const roster = page.locator('.educationRoster');
  await roster.locator('summary').click();
  page.once('dialog', (dialog) => dialog.dismiss());
  await roster.getByRole('button', { name: '移除人员', exact: true }).click();
  assert.equal(await roster.locator('.educationRosterPerson').count(), 1);
  page.once('dialog', (dialog) => dialog.accept());
  await roster.getByRole('button', { name: '移除人员', exact: true }).click();
  await page.getByRole('button', { name: '教练评估', exact: true }).click();
  await roster.locator('summary').click();
  await roster.getByText('暂无在册人员；此名册不创建登录账号。', { exact: true }).waitFor();
  await assessment.getByRole('button', { name: '阶段观察', exact: true }).click();
  assert.equal(await assessment.locator('[name="evaluator_staff_id"] option[value="teacher-1"]').count(), 0);
  await assessment.getByRole('button', { name: '结营评估', exact: true }).click();
  await assessment.getByRole('button', { name: '修改该评估', exact: true }).click();
  assert.equal(await assessment.locator('[name="evaluator_staff_id"]').inputValue(), 'teacher-1');
  assert.match(await assessment.locator('[name="evaluator_staff_id"] option:checked').innerText(), /已移除/);
  const desktop = path.join(os.tmpdir(), "jaos-education-desktop.png");
  await page.screenshot({ path: desktop, fullPage: true });
  await page.setViewportSize({ width: 390, height: 844 });
  assert.equal(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth), true);
  const mobile = path.join(os.tmpdir(), "jaos-education-mobile.png");
  await page.screenshot({ path: mobile, fullPage: true });
  await page.goto("http://127.0.0.1:4179/tests/education-ui.html?founder=1", { waitUntil: "domcontentloaded" });
  await page.getByRole("button", { name: /2026年10月托管教培班/ }).click();
  const deletion = page.locator('.educationCohortDelete');
  await deletion.locator('summary').click();
  await deletion.locator('[name="current_login_password"]').fill('fixture-login');
  await deletion.locator('[name="new_password"]').fill('fixture-delete');
  await deletion.locator('[name="confirm_password"]').fill('fixture-delete');
  await deletion.getByRole('button', { name: '设置删除密码', exact: true }).click();
  await deletion.locator('[name="confirm_name"]').fill('2026年10月托管教培班');
  await deletion.locator('[name="deletion_password"]').fill('fixture-delete');
  await deletion.locator('[name="reason"]').fill('重复创建的测试班期');
  page.once('dialog', (dialog) => dialog.dismiss());
  await deletion.getByRole('button', { name: '验证密码并删除班期', exact: true }).click();
  assert.equal(await page.locator('.educationCohortList button').count(), 1);
  page.once('dialog', (dialog) => dialog.accept());
  await deletion.getByRole('button', { name: '验证密码并删除班期', exact: true }).click();
  await page.getByText('班期已删除，已从日常页面及教培汇总移除；历史资料保留供追溯。', { exact: true }).waitFor();
  assert.equal(await page.locator('.educationCohortList button').count(), 0);
  assert.equal(await page.locator('.educationDetail').count(), 0);
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ status: "passed", desktop, mobile }));
} finally {
  await browser.close();
  await new Promise((resolve) => server.httpServer.close(resolve));
}
